// <auto-generated />
namespace EFRepositoryUnitOfWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Made_ReferencedTablesVirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Made_ReferencedTablesVirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141250177_Made_ReferencedTablesVirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
